input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    if (true) {
        basic.showLeds(`
            . . # . .
            . # # # .
            # . # . #
            . . # . .
            . . # . .
            `)
        basic.showLeds(`
            . . . . .
            . # # # .
            # . # . #
            . . # . .
            . . # . .
            `)
        basic.showLeds(`
            . . . . .
            . # . # .
            # . # . #
            . . # . .
            . . # . .
            `)
        basic.showLeds(`
            . . . . .
            . . . . .
            # . # . #
            . . # . .
            . . # . .
            `)
        basic.showLeds(`
            . . . . .
            . . . . .
            . . . . .
            . . # . .
            . . # . .
            `)
        basic.showLeds(`
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            . . # . .
            `)
        basic.showLeds(`
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            `)
        music.setVolume(255)
        cubo = game.createSprite(1, 4)
    } else {
    	
    }
})
input.onButtonPressed(Button.A, function () {
    music.setTempo(115)
    for (let index = 0; index < 2; index++) {
        music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(200)
        music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(60)
        music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(120)
        music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(120)
        music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(200)
        music.play(music.tonePlayable(131, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(131, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        music.rest(music.beat(BeatFraction.Quarter))
        basic.pause(80)
        music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(233, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(233, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(45)
        music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        music.rest(music.beat(BeatFraction.Eighth))
        basic.pause(45)
        music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        music.rest(music.beat(BeatFraction.Eighth))
        basic.pause(45)
        music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        music.rest(music.beat(BeatFraction.Quarter))
        basic.pause(80)
        music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
        music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(20)
        music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
        basic.pause(40)
    }
    music.play(music.tonePlayable(87.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(87.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(87.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    basic.pause(160)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(87.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(78, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(120)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(60)
    music.play(music.tonePlayable(78, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    basic.pause(60)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(200)
    music.play(music.tonePlayable(78, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(131, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(131, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(78, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(65.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(65.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.rest(music.beat(BeatFraction.Quarter))
    basic.pause(80)
    music.play(music.tonePlayable(65.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(65.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(233, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(233, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.rest(music.beat(BeatFraction.Eighth))
    basic.pause(45)
    music.play(music.tonePlayable(75.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.rest(music.beat(BeatFraction.Eighth))
    basic.pause(45)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.rest(music.beat(BeatFraction.Quarter))
    basic.pause(80)
    music.play(music.tonePlayable(75.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(75.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(87.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(87.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(87.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    basic.pause(160)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(87.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(78, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(120)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(60)
    music.play(music.tonePlayable(78, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    basic.pause(60)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(200)
    music.play(music.tonePlayable(78, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(131, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(131, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(156, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(78, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(175, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(65.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(65.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.rest(music.beat(BeatFraction.Quarter))
    basic.pause(80)
    music.play(music.tonePlayable(65.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(65.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(233, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(233, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(311, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.rest(music.beat(BeatFraction.Eighth))
    basic.pause(45)
    music.play(music.tonePlayable(75.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.rest(music.beat(BeatFraction.Eighth))
    basic.pause(45)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    music.rest(music.beat(BeatFraction.Quarter))
    basic.pause(80)
    music.play(music.tonePlayable(75.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(349, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(208, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.play(music.tonePlayable(75.5, music.beat(BeatFraction.Eighth)), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(20)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.setVolume(127)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.setVolume(59)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
    basic.pause(40)
    music.setVolume(59)
    music.play(music.tonePlayable(196, music.beat(BeatFraction.Eighth)), music.PlaybackMode.UntilDone)
})
input.onButtonPressed(Button.B, function () {
    cubo.change(LedSpriteProperty.Y, -1)
    basic.pause(100)
    if (input.buttonIsPressed(Button.B)) {
        cubo.change(LedSpriteProperty.Y, -1)
    } else if (cubo.get(LedSpriteProperty.Y) == 4) {
        cubo.change(LedSpriteProperty.Y, 0)
    } else {
        cubo.change(LedSpriteProperty.Y, 1)
    }
    basic.pause(100)
    if (input.buttonIsPressed(Button.B)) {
        cubo.change(LedSpriteProperty.Y, -1)
    } else if (cubo.get(LedSpriteProperty.Y) == 4) {
        cubo.change(LedSpriteProperty.Y, 0)
    } else {
        cubo.change(LedSpriteProperty.Y, 1)
    }
    basic.pause(100)
    if (input.buttonIsPressed(Button.B)) {
        cubo.change(LedSpriteProperty.Y, -1)
    } else if (cubo.get(LedSpriteProperty.Y) == 4) {
        cubo.change(LedSpriteProperty.Y, 0)
    } else {
        cubo.change(LedSpriteProperty.Y, 1)
    }
    basic.pause(100)
    if (input.buttonIsPressed(Button.B)) {
        cubo.change(LedSpriteProperty.Y, -1)
    } else if (cubo.get(LedSpriteProperty.Y) == 4) {
        cubo.change(LedSpriteProperty.Y, 0)
    } else {
        cubo.change(LedSpriteProperty.Y, 1)
    }
})
let cubo: game.LedSprite = null
basic.showLeds(`
    . . # . .
    . # # # .
    # . # . #
    . . # . .
    . . # . .
    `)
basic.forever(function () {
	
})
